-- Database console

-- all DELETE
DELETE FROM Resumes;
DELETE FROM Userinfos;
DELETE FROM Users;
ALTER TABLE Resumes AUTO_INCREMENT=1;
ALTER TABLE Userinfos AUTO_INCREMENT=1;
ALTER TABLE Users AUTO_INCREMENT=1;